export const fonts = {
  Black: 'AlbertSans-Black',
  BlackItalic: 'AlbertSans-BlackItalic',
  Bold: 'AlbertSans-Bold',
  BoldItalic: 'AlbertSans-BoldItalic',
  ExtraBold: 'AlbertSans-ExtraBold',
  ExtraBoldItalic: 'AlbertSans-ExtraBoldItalic',
  ExtraLight: 'AlbertSans-ExtraLight',
  ExtraLightItalic: 'AlbertSans-ExtraLightItalic',
  Italic: 'AlbertSans-Italic',
  Light: 'AlbertSans-Light',
  LightItalic: 'AlbertSans-LightItalic',
  Medium: 'AlbertSans-Medium',
  MediumItalic: 'AlbertSans-MediumItalic',
  Regular: 'AlbertSans-Regular',
  Semibold: 'AlbertSans-SemiBold',
  SemiboldItalic: 'AlbertSans-SemiBoldItalic',
  Thin: 'AlbertSans-Thin',
  ThinItalic: 'AlbertSans-ThinItalic',
};
