export const icons = {
  uk: require('../../assets/Images/UK.png'),
  google: require('../../assets/Images/Google.png'),
  apple: require('../../assets/Images/Apple.png'),
  back: require('../../assets/Images/Back.png'),
  OTPVerification: require('../../assets/Images/OtpVarification.png'),
  amoeba: require('../../assets/Images/amoeba.png'),
  frame1: require('../../assets/Images/frame1.png'),
  frame2: require('../../assets/Images/frame2.png'),
  frame3: require('../../assets/Images/frame3.png'),
  info: require('../../assets/Images/info.png'),
  Male: require('../../assets/Images/Male.png'),
  Female: require('../../assets/Images/Female.png'),
  arrow: require('../../assets/Images/Arrow.png'),
  Other: require('../../assets/Images/Other.png'),
};
